// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team_Project_4.Models;

#nullable disable

namespace Team_Project_4.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Team_Project_4.Models.Hoadon", b =>
                {
                    b.Property<int>("Mahd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahd"), 1L, 1);

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CCCD");

                    b.Property<int>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYDAT");

                    b.Property<DateTime>("Ngaylaphd")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAPHD");

                    b.Property<int>("Songayo")
                        .HasColumnType("int")
                        .HasColumnName("SONGAYO");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKH");

                    b.Property<string>("Tenphong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENPHONG");

                    b.Property<int>("Tongtien")
                        .HasColumnType("int")
                        .HasColumnName("TONGTIEN");

                    b.Property<double>("Tylephuthu")
                        .HasColumnType("float")
                        .HasColumnName("TYLEPHUTHU");

                    b.HasKey("Mahd");

                    b.HasIndex("Manv");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Khachhang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makh"), 1L, 1);

                    b.Property<string>("Cmndkh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CMNDKH");

                    b.Property<string>("Diachikh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHIKH");

                    b.Property<int>("Maloaikhach")
                        .HasColumnType("int")
                        .HasColumnName("MALOAIKHACH");

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("MAP");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("TEL");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENKH");

                    b.Property<int?>("Tuoi")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("TUOI");

                    b.HasKey("Makh")
                        .HasName("PK_KHACH");

                    b.HasIndex("Maloaikhach");

                    b.HasIndex("Map");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Loaikhach", b =>
                {
                    b.Property<int>("Maloaikhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALOAIKHACH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maloaikhach"), 1L, 1);

                    b.Property<string>("Tenloaikhach")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("TENLOAIKHACH")
                        .IsFixedLength();

                    b.HasKey("Maloaikhach");

                    b.ToTable("LOAIKHACH", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Loaiphong", b =>
                {
                    b.Property<int>("Maloaiphong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALOAIPHONG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maloaiphong"), 1L, 1);

                    b.Property<int?>("Dongia")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("DONGIA");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Maloaiphong");

                    b.ToTable("LOAIPHONG", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manv"), 1L, 1);

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("HOTEN");

                    b.Property<DateTime?>("Ngaysinh")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Phai")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("PHAI")
                        .IsFixedLength();

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("SDT");

                    b.HasKey("Manv");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Phieuthue", b =>
                {
                    b.Property<int>("Mapt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapt"), 1L, 1);

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CCCD");

                    b.Property<int>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("MAP");

                    b.Property<DateTime>("Ngaylappt")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAPPT");

                    b.HasKey("Mapt")
                        .HasName("PK_Table_1");

                    b.HasIndex("Makh");

                    b.HasIndex("Map");

                    b.ToTable("PHIEUTHUE", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Phong", b =>
                {
                    b.Property<int>("Map")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Map"), 1L, 1);

                    b.Property<string>("Ghichu")
                        .HasColumnType("text")
                        .HasColumnName("GHICHU");

                    b.Property<int>("Maloaiphong")
                        .HasColumnType("int")
                        .HasColumnName("MALOAIPHONG");

                    b.Property<int>("Soluongkhachtoida")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGKHACHTOIDA");

                    b.Property<int>("Songayo")
                        .HasColumnType("int")
                        .HasColumnName("SONGAYO");

                    b.Property<string>("Tenphong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENPHONG");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Map");

                    b.HasIndex("Maloaiphong");

                    b.ToTable("PHONG", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Phuthu", b =>
                {
                    b.Property<int>("Idphuthu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPhuthu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idphuthu"), 1L, 1);

                    b.Property<double?>("Giatriphuthu")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("Idphuthu");

                    b.ToTable("PHUTHU", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Taikhoan", b =>
                {
                    b.Property<int>("Matknv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATKNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matknv"), 1L, 1);

                    b.Property<int>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<string>("Mktk")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("MKTK")
                        .IsFixedLength();

                    b.Property<string>("Tentknv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)")
                        .HasColumnName("TENTKNV")
                        .IsFixedLength();

                    b.HasKey("Matknv");

                    b.HasIndex("Manv");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("Team_Project_4.Models.Hoadon", b =>
                {
                    b.HasOne("Team_Project_4.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Manv")
                        .IsRequired()
                        .HasConstraintName("FK_HOADON_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Khachhang", b =>
                {
                    b.HasOne("Team_Project_4.Models.Loaikhach", "MaloaikhachNavigation")
                        .WithMany("Khachhangs")
                        .HasForeignKey("Maloaikhach")
                        .IsRequired()
                        .HasConstraintName("FK_KHACHHANG_LOAIKHACH");

                    b.HasOne("Team_Project_4.Models.Phong", "MapNavigation")
                        .WithMany("Khachhangs")
                        .HasForeignKey("Map")
                        .IsRequired()
                        .HasConstraintName("FK_KHACHHANG_PHONG1");

                    b.Navigation("MaloaikhachNavigation");

                    b.Navigation("MapNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Phieuthue", b =>
                {
                    b.HasOne("Team_Project_4.Models.Khachhang", "MakhNavigation")
                        .WithMany("Phieuthues")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUTHUE_KHACHHANG1");

                    b.HasOne("Team_Project_4.Models.Phong", "MapNavigation")
                        .WithMany("Phieuthues")
                        .HasForeignKey("Map")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUTHUE_PHONG");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MapNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Phong", b =>
                {
                    b.HasOne("Team_Project_4.Models.Loaiphong", "MaloaiphongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("Maloaiphong")
                        .IsRequired()
                        .HasConstraintName("FK_PHONG_LOAIPHONG");

                    b.Navigation("MaloaiphongNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Taikhoan", b =>
                {
                    b.HasOne("Team_Project_4.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("Manv")
                        .IsRequired()
                        .HasConstraintName("FK_TAIKHOAN_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Team_Project_4.Models.Khachhang", b =>
                {
                    b.Navigation("Phieuthues");
                });

            modelBuilder.Entity("Team_Project_4.Models.Loaikhach", b =>
                {
                    b.Navigation("Khachhangs");
                });

            modelBuilder.Entity("Team_Project_4.Models.Loaiphong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("Team_Project_4.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("Team_Project_4.Models.Phong", b =>
                {
                    b.Navigation("Khachhangs");

                    b.Navigation("Phieuthues");
                });
#pragma warning restore 612, 618
        }
    }
}
